# Generated by Django 4.2.7 on 2023-11-21 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AracTipi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=100, verbose_name='Adı')),
                ('kapasite', models.IntegerField(verbose_name='Kapasite')),
            ],
            options={
                'verbose_name': 'Araç Tipi',
                'verbose_name_plural': 'Araç Tipleri',
            },
        ),
        migrations.CreateModel(
            name='Departman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=100, verbose_name='Departman')),
            ],
            options={
                'verbose_name': 'Departman',
                'verbose_name_plural': 'Departmanlar',
            },
        ),
        migrations.CreateModel(
            name='Il',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=100, verbose_name='Adı')),
            ],
            options={
                'verbose_name': 'İl',
                'verbose_name_plural': 'İller',
            },
        ),
        migrations.CreateModel(
            name='Lokasyon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=100, verbose_name='Adı')),
                ('il', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpsManager.il', verbose_name='İl')),
            ],
            options={
                'verbose_name': 'Lokasyon',
                'verbose_name_plural': 'Lokasyonlar',
            },
        ),
        migrations.CreateModel(
            name='Musteri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Ad')),
                ('soyad', models.CharField(max_length=100, verbose_name='Soyad')),
                ('tel', models.CharField(max_length=15, verbose_name='Telefon')),
                ('mail', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('musteri_tipi', models.CharField(choices=[('Xiaohongshu', 'Xiaohongshu'), ('Ctrip', 'Ctrip'), ('Bireysel', 'Bireysel'), ('Acenta', 'Acenta'), ('Surekli Acenta', 'Sürekli Acenta')], default='Acenta', max_length=20, verbose_name='Müşteri Tipi')),
            ],
            options={
                'verbose_name': 'Müşteri',
                'verbose_name_plural': 'Müşteriler',
            },
        ),
        migrations.CreateModel(
            name='Otel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=100, verbose_name='Adı')),
                ('tek_kisilik_oda_ucreti', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tek Kişilik Oda Ücreti')),
                ('cift_kisilik_oda_ucreti', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Çift Kişilik Oda Ücreti')),
                ('yildiz_sayisi', models.IntegerField(verbose_name='Yıldız Sayısı')),
                ('lokasyon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpsManager.lokasyon', verbose_name='Lokasyon')),
            ],
            options={
                'verbose_name': 'Otel',
                'verbose_name_plural': 'Oteller',
            },
        ),
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OpsManager.departman', verbose_name='Departman')),
            ],
            options={
                'verbose_name': 'Personel',
                'verbose_name_plural': 'Personeller',
            },
        ),
        migrations.CreateModel(
            name='Rehber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=100, verbose_name='Adı')),
                ('ucreti', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ücreti')),
                ('il', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpsManager.il', verbose_name='İl')),
            ],
            options={
                'verbose_name': 'Rehber',
                'verbose_name_plural': 'Rehberler',
            },
        ),
        migrations.CreateModel(
            name='SabitGider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=100, verbose_name='Adı')),
                ('fiyati', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyatı')),
            ],
            options={
                'verbose_name': 'Sabit Gider',
                'verbose_name_plural': 'Sabit Giderler',
            },
        ),
        migrations.CreateModel(
            name='Satis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslangic_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Başlangıç Tarihi')),
                ('bitis_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Toplam Fiyat')),
                ('alici_musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpsManager.musteri', verbose_name='Alıcı Müşteri')),
                ('sabit_giderler', models.ManyToManyField(blank=True, to='OpsManager.sabitgider', verbose_name='Sabit Giderler')),
                ('satici_personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpsManager.personel', verbose_name='Satıcı Personel')),
            ],
            options={
                'verbose_name': 'Satış',
                'verbose_name_plural': 'Satışlar',
            },
        ),
        migrations.CreateModel(
            name='Sirket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=100, verbose_name='Şirket')),
                ('is_active', models.BooleanField(default=False)),
                ('baslangic_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Başlangıç Tarihi')),
                ('bitis_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='YolcuBilgileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasaport', models.CharField(max_length=75, verbose_name='Pasaport')),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpsManager.musteri', verbose_name='Müşteriler')),
                ('sirket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpsManager.sirket', verbose_name='Şirket')),
            ],
            options={
                'verbose_name': 'Yolcu Bilgisi',
                'verbose_name_plural': 'Yolcu Bilgileri',
            },
        ),
        migrations.CreateModel(
            name='Tur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=100, verbose_name='Adı')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('fiyati', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyatı')),
                ('lokasyon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpsManager.lokasyon', verbose_name='Lokasyon')),
                ('sirket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpsManager.sirket', verbose_name='Şirket')),
            ],
            options={
                'verbose_name': 'Tur',
                'verbose_name_plural': 'Turlar',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guzergah', models.CharField(max_length=100, verbose_name='Güzergah')),
                ('fiyat_5_koltuk', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fiyat (5 Koltuk)')),
                ('fiyat_7_koltuk', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fiyat (7 Koltuk)')),
                ('fiyat_9_koltuk', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fiyat (9 Koltuk)')),
                ('fiyat_12_koltuk', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fiyat (12 Koltuk)')),
                ('fiyat_15_koltuk', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fiyat (15 Koltuk)')),
                ('fiyat_16_20_koltuk', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fiyat (16-20 Koltuk)')),
                ('sirket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpsManager.sirket', verbose_name='Şirket')),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transferler',
            },
        ),
        migrations.CreateModel(
            name='SatisItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gun', models.CharField(blank=True, max_length=3, null=True, verbose_name='Gün')),
                ('islem_turu', models.CharField(choices=[('Karşılama', 'Karşılama'), ('Araç', 'Araç'), ('Tur', 'Tur'), ('Uğurlama', 'Uğurlama'), ('Serbest Zaman', 'Serbest Zaman'), ('Aktivite', 'Aktivite'), ('Çince Şoför', 'Çince Şoför'), ('Tercüman', 'Tercüman')], max_length=50, verbose_name='İşlem Türü')),
                ('aciklama', models.CharField(blank=True, max_length=250, null=True, verbose_name='Açıklama')),
                ('otel_turu', models.CharField(choices=[('Tek', 'Tek'), ('Çift', 'Çift')], default='Tek', max_length=50, verbose_name='Otel Türü')),
                ('fiyat', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Fiyat')),
                ('arac_tipi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OpsManager.aractipi', verbose_name='Araç Tipi')),
                ('oteller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OpsManager.otel', verbose_name='Otel')),
                ('rehber', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OpsManager.rehber', verbose_name='Rehber')),
                ('satis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpsManager.satis', verbose_name='Satış')),
                ('sirket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpsManager.sirket', verbose_name='Şirket')),
                ('transferler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OpsManager.transfer', verbose_name='Transfer')),
                ('turlar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OpsManager.tur', verbose_name='Tur')),
            ],
            options={
                'verbose_name': 'Satış İtem',
                'verbose_name_plural': 'Satış İtemler',
            },
        ),
        migrations.AddField(
            model_name='satis',
            name='sirket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpsManager.sirket', verbose_name='Şirket'),
        ),
        migrations.AddField(
            model_name='satis',
            name='yolcular',
            field=models.ManyToManyField(default=None, to='OpsManager.yolcubilgileri', verbose_name='Yolcu Bilgileri'),
        ),
        migrations.AddField(
            model_name='sabitgider',
            name='sirket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpsManager.sirket', verbose_name='Şirket'),
        ),
        migrations.AddField(
            model_name='rehber',
            name='sirket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpsManager.sirket', verbose_name='Şirket'),
        ),
        migrations.AddField(
            model_name='personel',
            name='sirket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpsManager.sirket', verbose_name='Şirket'),
        ),
        migrations.AddField(
            model_name='personel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='otel',
            name='sirket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpsManager.sirket', verbose_name='Şirket'),
        ),
        migrations.AddField(
            model_name='musteri',
            name='sirket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpsManager.sirket', verbose_name='Şirket'),
        ),
        migrations.AddField(
            model_name='lokasyon',
            name='sirket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpsManager.sirket', verbose_name='Şirket'),
        ),
        migrations.AddField(
            model_name='il',
            name='sirket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpsManager.sirket', verbose_name='Şirket'),
        ),
        migrations.AddField(
            model_name='departman',
            name='sirket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpsManager.sirket', verbose_name='Şirket'),
        ),
        migrations.AddField(
            model_name='aractipi',
            name='sirket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpsManager.sirket', verbose_name='Şirket'),
        ),
    ]
