# Generated by Django 4.2.7 on 2023-11-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpsManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sirket',
            options={'verbose_name': 'Şirket', 'verbose_name_plural': 'Şirketler'},
        ),
        migrations.AddField(
            model_name='personel',
            name='is_ceo',
            field=models.BooleanField(default=False, verbose_name='Yetkili mi?'),
        ),
    ]
