# Generated by Django 4.2.7 on 2023-11-22 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OpsManager', '0002_alter_sirket_options_personel_is_ceo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satis',
            name='yolcular',
        ),
        migrations.AddField(
            model_name='satis',
            name='yolcu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OpsManager.yolcubilgileri', verbose_name='Yolcu Bilgisi'),
        ),
        migrations.CreateModel(
            name='DigerYolcuBilgileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Ad')),
                ('soyad', models.CharField(max_length=100, verbose_name='Soyad')),
                ('tel', models.CharField(max_length=15, verbose_name='Telefon')),
                ('pasaport', models.CharField(max_length=75, verbose_name='Pasaport')),
                ('sirket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpsManager.sirket', verbose_name='Şirket')),
            ],
            options={
                'verbose_name': 'Diğer Yolcu Bilgisi',
                'verbose_name_plural': 'Diğer Yolcu Bilgileri',
            },
        ),
        migrations.AddField(
            model_name='satis',
            name='digeryolcular',
            field=models.ManyToManyField(to='OpsManager.digeryolcubilgileri', verbose_name='Diğer Yolcu Bilgileri'),
        ),
    ]
