# Generated by Django 4.1.3 on 2023-11-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpsManager', '0004_satis_satildi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satis',
            name='digeryolcular',
            field=models.ManyToManyField(blank=True, null=True, to='OpsManager.digeryolcubilgileri', verbose_name='Diğer Yolcu Bilgileri'),
        ),
    ]
