# Generated by Django 4.2.7 on 2023-11-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpsManager', '0005_alter_satis_digeryolcular'),
    ]

    operations = [
        migrations.AddField(
            model_name='satisitem',
            name='saat',
            field=models.TimeField(blank=True, null=True, verbose_name='Saat'),
        ),
    ]
