# Generated by Django 4.2.7 on 2023-11-24 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OpsManager', '0007_fiyatlandırma_fiyatlandirmaitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fiyatlandirmaitem',
            old_name='arac_fiyatı',
            new_name='arac_fiyati',
        ),
        migrations.RenameField(
            model_name='fiyatlandirmaitem',
            old_name='double_oda_fiyatı',
            new_name='double_oda_fiyati',
        ),
        migrations.RenameField(
            model_name='fiyatlandirmaitem',
            old_name='rehber_fiyatı',
            new_name='rehber_fiyati',
        ),
        migrations.RenameField(
            model_name='fiyatlandirmaitem',
            old_name='single_oda_fiyatı',
            new_name='single_oda_fiyati',
        ),
        migrations.RenameField(
            model_name='fiyatlandirmaitem',
            old_name='transfer_fiyatı',
            new_name='transfer_fiyati',
        ),
        migrations.RenameField(
            model_name='fiyatlandirmaitem',
            old_name='yemek_fiyatı',
            new_name='yemek_fiyati',
        ),
    ]
