# Generated by Django 4.2.7 on 2023-11-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpsManager', '0008_rename_arac_fiyatı_fiyatlandirmaitem_arac_fiyati_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiyatlandirmaitem',
            name='aciklama',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='fiyatlandirmaitem',
            name='arac_fiyati',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Araç Fiyatı'),
        ),
        migrations.AlterField(
            model_name='fiyatlandirmaitem',
            name='double_oda_fiyati',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Double Oda Fiyatı'),
        ),
        migrations.AlterField(
            model_name='fiyatlandirmaitem',
            name='rehber_fiyati',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rehber Fiyatı'),
        ),
        migrations.AlterField(
            model_name='fiyatlandirmaitem',
            name='single_oda_fiyati',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Single Oda Fiyatı'),
        ),
        migrations.AlterField(
            model_name='fiyatlandirmaitem',
            name='tarih',
            field=models.DateField(blank=True, null=True, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='fiyatlandirmaitem',
            name='transfer_fiyati',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Transfer Fiyatı'),
        ),
        migrations.AlterField(
            model_name='fiyatlandirmaitem',
            name='yemek_fiyati',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Yemek Fiyatı'),
        ),
        migrations.AlterField(
            model_name='fiyatlandırma',
            name='arac_toplam',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Araç Fiyatı'),
        ),
        migrations.AlterField(
            model_name='fiyatlandırma',
            name='double_oda_toplam',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Double Oda Toplam Fiyatı'),
        ),
        migrations.AlterField(
            model_name='fiyatlandırma',
            name='genel_toplam',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Genel Toplam Fiyatı'),
        ),
        migrations.AlterField(
            model_name='fiyatlandırma',
            name='rehber_toplam',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rehber Toplam Fiyatı'),
        ),
        migrations.AlterField(
            model_name='fiyatlandırma',
            name='single_oda_toplam',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Single Oda Toplam Fiyatı'),
        ),
        migrations.AlterField(
            model_name='fiyatlandırma',
            name='transfer_toplam',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Transfer Toplam Fiyatı'),
        ),
        migrations.AlterField(
            model_name='fiyatlandırma',
            name='tur_toplam',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tur Toplam Fiyatı'),
        ),
        migrations.AlterField(
            model_name='fiyatlandırma',
            name='yemek_toplam',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Yemek Toplam Fiyatı'),
        ),
    ]
