# Generated by Django 4.2.7 on 2023-11-24 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OpsManager', '0009_alter_fiyatlandirmaitem_aciklama_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiyatlandirmaitem',
            name='sirket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OpsManager.sirket', verbose_name='Şirket'),
        ),
        migrations.AddField(
            model_name='fiyatlandırma',
            name='olusturan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OpsManager.personel', verbose_name='Personel'),
        ),
        migrations.AddField(
            model_name='fiyatlandırma',
            name='sirket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OpsManager.sirket', verbose_name='Şirket'),
        ),
    ]
