# Generated by Django 4.2.7 on 2023-11-24 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OpsManager', '0010_fiyatlandirmaitem_sirket_fiyatlandırma_olusturan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiyatlandırma',
            name='tur_toplam',
        ),
    ]
