# Generated by Django 4.2.7 on 2023-11-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpsManager', '0011_remove_fiyatlandırma_tur_toplam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiyatlandirmaitem',
            options={'verbose_name': 'Fiyatlandırma Item', 'verbose_name_plural': 'Fiyatlandırma Itemleri'},
        ),
        migrations.AlterModelOptions(
            name='fiyatlandırma',
            options={'verbose_name': 'Fiyatlandırma', 'verbose_name_plural': 'Fiyatlandırmalar'},
        ),
        migrations.AlterField(
            model_name='satisitem',
            name='gun',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tarih'),
        ),
    ]
