# Generated by Django 4.2.7 on 2023-11-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpsManager', '0012_alter_fiyatlandirmaitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiyatlandırma',
            name='onay',
            field=models.BooleanField(default=False, verbose_name='Onay'),
        ),
    ]
