# Generated by Django 4.2.7 on 2023-11-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpsManager', '0013_fiyatlandırma_onay'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiyatlandırma',
            name='islem',
            field=models.BooleanField(default=False, verbose_name='Onay'),
        ),
    ]
