# Generated by Django 4.1.3 on 2023-11-26 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OpsManager', '0016_fiyatlandırma_aciklama'),
    ]

    operations = [
        migrations.AddField(
            model_name='satis',
            name='takip_personel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='satislar_takipci', to='OpsManager.personel', verbose_name='Takip Eden Personel'),
        ),
        migrations.AlterField(
            model_name='satis',
            name='digeryolcular',
            field=models.ManyToManyField(to='OpsManager.digeryolcubilgileri', verbose_name='Diğer Yolcu Bilgileri'),
        ),
        migrations.AlterField(
            model_name='satis',
            name='satici_personel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satislar_satici', to='OpsManager.personel', verbose_name='Satıcı Personel'),
        ),
    ]
